# Generated by Django 4.2.3 on 2023-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('idcalendario', models.CharField(db_column='idCalendario', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'calendario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FechasSolicitadas',
            fields=[
                ('idfechassolicitadas', models.CharField(db_column='idFechasSolicitadas', max_length=45, primary_key=True, serialize=False)),
                ('fechainicial', models.DateTimeField(db_column='FechaInicial')),
                ('fechafinal', models.DateTimeField(db_column='FechaFinal')),
                ('rut', models.CharField(db_column='Rut', max_length=10)),
                ('numerodecontacto', models.CharField(db_column='NumeroDeContacto', max_length=12)),
                ('nombremascota', models.CharField(db_column='nombreMascota', max_length=45)),
            ],
            options={
                'db_table': 'fechassolicitadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('idfranquicia', models.CharField(db_column='idFranquicia', max_length=45, primary_key=True, serialize=False)),
                ('nombrefranquicia', models.CharField(blank=True, db_column='nombreFranquicia', max_length=45, null=True)),
            ],
            options={
                'db_table': 'franquicia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('idinsumos', models.CharField(db_column='idInsumos', max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDeOperaciones',
            fields=[
                ('idregistrodeoperaciones', models.CharField(db_column='idRegistroDeOperaciones', max_length=45, primary_key=True, serialize=False)),
                ('operación', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'registrodeoperaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroVacunasSuministradas',
            fields=[
                ('idvacunassuministradas', models.CharField(db_column='idVacunasSuministradas', max_length=45, primary_key=True, serialize=False)),
                ('nombrevacuna', models.CharField(db_column='nombreVacuna', max_length=45)),
            ],
            options={
                'db_table': 'registrovacunassuministradas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaMedica',
            fields=[
                ('idtablamedica', models.CharField(db_column='idTablaMedica', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tablamedica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('idveterinaria', models.CharField(db_column='idVeterinaria', max_length=45, primary_key=True, serialize=False)),
                ('nombreveterinaria', models.CharField(db_column='nombreVeterinaria', max_length=45, unique=True)),
                ('direccion', models.CharField(db_column='Direccion', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'veterinaria',
                'managed': False,
            },
        ),
    ]
