# Generated by Django 4.2.3 on 2023-10-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_fechascalendario_delete_calendario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('idmedicamentos', models.IntegerField(db_column='idMedicamentos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('valor', models.IntegerField(db_column='valor')),
                ('cantidad', models.IntegerField(db_column='cantidad')),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
    ]
