# Generated by Django 4.2.3 on 2023-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_medicamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosVenta',
            fields=[
                ('idproductosventa', models.IntegerField(db_column='idProductosVenta', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=13)),
                ('cantidad', models.CharField(db_column='cantidad', max_length=45)),
                ('valor', models.IntegerField(db_column='valor')),
            ],
            options={
                'db_table': 'productosventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroDeVentas',
            fields=[
                ('idregistrodeventas', models.IntegerField(db_column='idRegistroDeVentas', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(db_column='fecha')),
                ('valortotal', models.IntegerField(db_column='valorTotal')),
                ('rutDueno', models.CharField(db_column='rutDueño', max_length=13)),
                ('nombreDueno', models.CharField(db_column='nombreDueño', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('correo', models.CharField(db_column='correo', max_length=45, null=True)),
            ],
            options={
                'db_table': 'RegistroDeVentas',
                'managed': False,
            },
        ),
    ]
