# Generated by Django 4.2.3 on 2023-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaHospitalizacion',
            fields=[
                ('idfichahospitalización', models.CharField(db_column='idFichaHospitalización', max_length=45, primary_key=True, serialize=False)),
                ('motivohospitalización', models.TextField(db_column='motivoHospitalización')),
                ('fechaultimamod', models.DateTimeField(blank=True, db_column='fechaUltimaMod', null=True)),
                ('flagmodificacion', models.IntegerField(blank=True, db_column='flagModificacion', null=True)),
            ],
            options={
                'db_table': 'fichahospitalización',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('idfichamedica', models.CharField(db_column='idFichaMedica', max_length=45, primary_key=True, serialize=False)),
                ('sucursalveterinaria', models.CharField(db_column='sucursalVeterinaria', max_length=45)),
                ('veterinarioacargo', models.CharField(db_column='veterinarioACargo', max_length=45)),
                ('fechaconsulta', models.DateTimeField(db_column='fechaConsulta')),
                ('operación', models.IntegerField()),
                ('frecuenciarespiratoria', models.CharField(db_column='frecuenciaRespiratoria', max_length=45)),
                ('frecuenciacardiaca', models.CharField(db_column='frecuenciaCardiaca', max_length=45)),
                ('peso', models.CharField(max_length=45)),
                ('edad', models.CharField(db_column='Edad', max_length=45)),
                ('hospitalización', models.IntegerField()),
                ('sedación', models.IntegerField()),
                ('temperatura', models.CharField(max_length=45)),
                ('fechaultimamod', models.DateTimeField(blank=True, db_column='fechaUltimaMod', null=True)),
                ('flagmodificacion', models.IntegerField(blank=True, db_column='flagModificacion', null=True)),
            ],
            options={
                'db_table': 'fichamedica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaOperacion',
            fields=[
                ('idfichaoperación', models.CharField(db_column='idFichaOperación', max_length=45, primary_key=True, serialize=False)),
                ('diagnostico', models.TextField()),
                ('cirugiaarealizar', models.CharField(db_column='cirugiaARealizar', max_length=45)),
                ('autorizaciontutor', models.IntegerField(db_column='autorizacionTutor')),
                ('fechaultimamod', models.DateTimeField(blank=True, db_column='fechaUltimaMod', null=True)),
                ('flagmodificacion', models.IntegerField(blank=True, db_column='flagModificacion', null=True)),
            ],
            options={
                'db_table': 'fichaoperación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fichasedacion',
            fields=[
                ('idfichasedación', models.CharField(db_column='idFichaSedación', max_length=45, primary_key=True, serialize=False)),
                ('autorizacióntutor', models.IntegerField(db_column='autorizaciónTutor')),
            ],
            options={
                'db_table': 'fichasedación',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentosConsulta',
            fields=[
                ('idmedicamentosconsulta', models.CharField(db_column='idMedicamentosConsulta', max_length=45, primary_key=True, serialize=False)),
                ('nombremedicamentos', models.CharField(db_column='nombreMedicamentos', max_length=45)),
            ],
            options={
                'db_table': 'medicamentosconsulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('idrecetamedica', models.CharField(db_column='idRecetaMedica', max_length=45, primary_key=True, serialize=False)),
                ('rutveterinario', models.CharField(db_column='rutVeterinario', max_length=10)),
                ('prescripcion', models.TextField()),
            ],
            options={
                'db_table': 'recetamedica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TratamientosConsulta',
            fields=[
                ('idtratamientosconsulta', models.CharField(db_column='idTratamientosConsulta', max_length=45, primary_key=True, serialize=False)),
                ('nombretratamientos', models.CharField(db_column='nombreTratamientos', max_length=45)),
                ('caudadelavisita', models.TextField(db_column='caudaDeLaVisita')),
            ],
            options={
                'db_table': 'tratamientosconsulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacunasSuministradasConsulta',
            fields=[
                ('idvacunassuministradas', models.CharField(db_column='idVacunasSuministradas', max_length=45, primary_key=True, serialize=False)),
                ('nombrevacuna', models.CharField(db_column='nombreVacuna', max_length=45)),
            ],
            options={
                'db_table': 'vacunassuministradasconsulta',
                'managed': False,
            },
        ),
    ]
