# Generated by Django 4.2.3 on 2023-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDueno',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuariodueño',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioVeterinario',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('admin', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarioveterinario',
                'managed': False,
            },
        ),
    ]
