# Generated by Django 4.2.3 on 2023-08-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('idalergias', models.CharField(db_column='idAlergias', max_length=45, primary_key=True, serialize=False)),
                ('nombrealergia', models.CharField(db_column='nombreAlergia', max_length=45)),
            ],
            options={
                'db_table': 'alergias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.CharField(db_column='idMascota', max_length=15, primary_key=True, serialize=False)),
                ('nombremascota', models.CharField(db_column='nombreMascota', max_length=45)),
                ('especie', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('fechadenacimiento', models.DateField(db_column='FechaDeNacimiento')),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
    ]
